.TH lvsnap 1
.SH NAME
lvsnap \- a wrapper for managing LVM snapshots
.SH SYNOPSIS
.B lvsnap
[\fB\-v\fR]
[\fB\-d\fR]
[\fB\-c\fR \fICONFIG\fR]
.IR ACTION
.SH DESCRIPTION
.B lvsnap
creates snapshots of partitions. It can snapshot devices using LVM. For
non-LVM devices it will use rsync to create a backup.

.B lvsnap
requires an
.B ACTION
as a positional argument. This can be one of the following:

.TP
.B create
creates a new snapshot

.TP
.B drop
drops the current snapshot

.TP
.B restore
restores the current snapshot

.SH OPTIONS
.TP
.BR \-v
Set verbosity on. Shows the commands which are run, among other usefull information.

.TP
.BR \-d
Dry-run. Do not execute the commands

.TP
.BR \-h
Include /home

.TP
.BR \-e
Include /boot/efi

.TP
.BR \-x " " \fIPATTERN\fR
Exclude device or mountpoints with PATTERN. Can be used multiple times.
